wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1680633178.848381
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.10.10
      5: 0.14.0
      8:
      - 5
    visualize:
      conf_mat:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: conf_mat_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: XRay Dataset
depth:
  desc: null
  value: 10
dropout:
  desc: null
  value: 0.35
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 3.0e-05
